import { test, expect } from '@playwright/test'

test('login, pages, edit, execute HTTP suite and download report', async ({ page }) => {
  const errors: string[] = []
  page.on('pageerror', error => errors.push(error.message))
  await page.goto('/login')
  await page.getByLabel('账号', {exact:true}).fill(process.env.AXIOM_ADMIN_USER || 'admin')
  await page.getByLabel('密码', {exact:true}).fill(process.env.AXIOM_ADMIN_PASSWORD || 'Axiom-Local-2026!')
  await page.getByRole('button', {name:'登录工作空间'}).click()
  await expect(page.getByRole('heading', {name:'工作台',exact:true})).toBeVisible()
  await page.screenshot({path:'test-results/dashboard.png',fullPage:true})
  for (const [path,title] of [['projects','项目管理'],['endpoints','接口管理'],['cases','测试用例'],['environments','环境配置'],['users','用户管理'],['roles','角色权限']]) {
    await page.goto('/' + path)
    await expect(page.getByRole('heading',{name:title,exact:true})).toBeVisible()
    await expect(page.locator('.el-loading-mask')).toHaveCount(0)
  }
  await page.goto('/endpoints')
  await expect(page.getByText('health_check',{exact:true})).toBeVisible()
  await expect(page.getByText('device_echo',{exact:true})).toBeVisible()
  await page.getByRole('button',{name:'编辑',exact:true}).first().click()
  await expect(page.getByRole('heading',{name:'编辑接口'})).toBeVisible()
  await page.getByRole('button',{name:'保存接口'}).click()
  await expect(page.getByText('保存成功',{exact:true})).toBeVisible()
  await page.goto('/cases')
  await page.screenshot({path:'test-results/cases.png',fullPage:true})
  await page.goto('/suites')
  await page.getByRole('button',{name:'执行',exact:true}).first().click()
  await page.getByRole('button',{name:'开始执行',exact:true}).click()
  await expect(page).toHaveURL(/runs\/[0-9]+/)
  await expect(page.locator('.run-summary .status-badge')).toHaveText('通过',{timeout:30000})
  await expect(page.locator('.result-title')).toHaveCount(2)
  const downloadPromise = page.waitForEvent('download')
  await page.getByRole('button',{name:'下载报告'}).click()
  const download = await downloadPromise
  expect(download.suggestedFilename()).toMatch(/axiom-report-\d+\.html/)
  await page.screenshot({path:'test-results/report.png',fullPage:true})
  expect(errors).toEqual([])
})

test('environment and role pages use frontend-facing permissions', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('账号', {exact:true}).fill(process.env.AXIOM_ADMIN_USER || 'admin')
  await page.getByLabel('密码', {exact:true}).fill(process.env.AXIOM_ADMIN_PASSWORD || 'Axiom-Local-2026!')
  await page.getByRole('button', {name:'登录工作空间'}).click()
  await expect(page.getByRole('heading', {name:'工作台',exact:true})).toBeVisible()
  await page.goto('/projects')
  await expect(page.getByRole('button',{name:'当前项目',exact:true})).toBeDisabled()
  await expect(page.getByRole('link',{name:'操作审计'})).toHaveCount(0)
  await page.goto('/environments')
  await expect(page.locator('.panel-tabs .active-tab')).toContainText('环境信息')
  await expect(page.getByRole('columnheader',{name:'我的环境变量'})).toBeVisible()
  await expect(page.getByRole('combobox',{name:'当前环境'})).toBeVisible()
  await page.goto('/roles')
  await page.getByRole('button',{name:'编辑',exact:true}).first().click()
  await expect(page.getByText('/endpoints',{exact:true})).toBeVisible()
  await expect(page.getByText('接口管理',{exact:true})).toBeVisible()
  await expect(page.getByText('公共基础环境固定由超级管理员维护', {exact:false})).toBeVisible()
})

test('environment uses systems and infrastructure while endpoints bind a system key', async ({ page }) => {
  await page.goto('/login')
  await page.getByLabel('账号', {exact:true}).fill(process.env.AXIOM_ADMIN_USER || 'admin')
  await page.getByLabel('密码', {exact:true}).fill(process.env.AXIOM_ADMIN_PASSWORD || 'Axiom-Local-2026!')
  await page.getByRole('button', {name:'登录工作空间'}).click()
  await expect(page.getByRole('heading', {name:'工作台',exact:true})).toBeVisible()
  await page.goto('/environments')
  await page.getByRole('button',{name:'编辑',exact:true}).first().click()
  await expect(page.getByText('系统配置',{exact:true})).toBeVisible()
  await expect(page.getByText('基础设施连接',{exact:true})).toBeVisible()
  await expect(page.getByText('基础地址',{exact:true})).toHaveCount(0)
  await page.getByRole('button',{name:'取消',exact:true}).click()
  await page.goto('/endpoints')
  await page.getByRole('button',{name:'编辑',exact:true}).first().click()
  await expect(page.getByRole('combobox',{name:'所属系统 Key'})).toHaveCount(0)
  await expect(page.getByText('当前环境：',{exact:false})).toBeVisible()
})
